version: "3.9"
services:
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-database
      - ME_CONFIG_OPTIONS_EDITORTHEME=material
      - ME_CONFIG_MONGODB_AUTH_DATABASE=graphql_db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
  mongodb-database:
    image: mongo:5.0.7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-graphql-db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=graphql_db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
  mongo-graphql-db: